---
replicaCount: 1

################################## IMAGE properties #####################################

image:
  repository: "192.168.234.47/kb-poc-kibana"
  tag: "1.4"
  pullPolicy: IfNotPresent

################################ Kibana container vars ##################################

deployment:
  name: kibana
  server_name: kb-kibana
  server_host: 0.0.0.0
  server_port: 5601
  es_ssl_verificationmode: none

livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 1
  httpGet:
    path: /app/kibana
    port: 5601
    scheme: HTTP

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 6
  failureThreshold: 1
  httpGet:
    path: /app/kibana
    port: 5601
    scheme: HTTP

################################# Service variables #####################################

service:
  name: kibana
  type: LoadBalancer
  port: 5601
  httpPort: 5601
  targetPort: 5601
  nodePort: 30234
#  labels: {}
#  annotations: {}
#  loadBalancerSourceRanges: []
    # 0.0.0.0/0

serviceAccount:
  create: false
  name: kibana-sa

############################### PV and PVC variables ####################################

persistentVolume:
  name: kibana-volume
  type: local
  capacity: 10Gi
  accessModes: ReadWriteOnce
  ReclaimPolicy: Delete
  hostPath:
    path: /mnt/kb-poc-share/kb-kibana

persistentVolumeClaim:
  name: kibana-pvc
  accessModes: ReadWriteOnce
  storage: 5Gi

volumeMounts:
  pv:
    mountPath: /usr/share/kibana/data

################################### INGRESS variables ###################################

ingress:
  enabled: false
  name: kibana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  host: kibana.kb.dev.com
  http:
    paths:
      backend:
        servicePort: 5601
                    
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
         
################################### Security variables ##################################

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 1000
  privileged: true

secretName: kibana-credentials

################################## Resources variables ##################################

resources: 
  limits:
    cpu: 1000m
  requests:
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: ""
fullnameOverride: ""
