{{- if .Values.persistentVolumeClaim.created }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "persistentVolumeClaimName" . }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
  volumeName: {{ include "persistentVolumeName" . }}
{{- end }}
