apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.httpPortName | default "http" }}
      protocol: TCP
      port: {{ .Values.httpPort }}
      {{- if .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
    - name: {{ .Values.service.transportPortName | default "transport" }}
      protocol: TCP
      port: {{ .Values.transportPort }}
    
  selector:
    app: elasticsearch
