{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kb-elastic.serviceAccountName" . }}
  labels:
{{ include "kb-elastic.labels" . | indent 4 }}
{{- end -}}
