{{- if .Values.master.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "masterServiceAccountName" . }}
  labels:
{{ include "elasticsearch.labels" . | indent 4 }}
    role: master
{{- end -}}
---
{{- if .Values.data.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dataServiceAccountName" . }}
  labels:
{{ include "elasticsearch.labels" . | indent 4 }}
    role: data
{{- end -}}
---
{{- if .Values.ingest.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingestServiceAccountName" . }}
  labels:
{{ include "elasticsearch.labels" . | indent 4 }}
    role: ingest
{{- end -}}
