---
{{- if .Values.data.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "dataStatefulSetName" . }}
spec:
  serviceName: {{ include "dataServiceName" . }}
  selector:
    matchLabels:
      app: {{ include "dataServiceName" . }}
  replicas: {{ .Values.data.replicaCount }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  {{- if not .Values.persistentVolumeClaim.created }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.volumeClaimTemplates.name }}
      spec:
        accessModes:
          - {{ .Values.volumeClaimTemplates.accessModes }}
        resources:
          requests:
            storage: {{ .Values.volumeClaimTemplates.resources.storage }}
          {{- if .Values.persistentVolume.created }}
          selector:
            matchLabels:
              volume: {{ include "persistentVolumeName" . }}
          {{- end }}
  {{- end }}
  template:
    metadata:
      labels: 
        app: {{ include "dataStatefulSetName" . }}
    spec:
      volumes:
        - name: elasticsearch-config
          configMap:
            name: {{  include "esConfigMapName" . }}
        - name: readonlyrest-config
          configMap:
            name: {{ include "rorConfigMapName" . }}
        - name: ror-keystore
          configMap:
            name: {{ include "rorKeystoreConfigMapName" . }}
        {{- if .Values.persistentVolumeClaim.created }}
        - name: {{ include "persistentVolumeName" . }}
          persistentVolumeClaim:
            claimName: {{ include "persistentVolumeClaimName" . }}
        {{- end }}
      containers:
        - name: elasticsearch
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              readOnly: true
              subPath: elasticsearch.yml
            - name: readonlyrest-config
              mountPath: /usr/share/elasticsearch/config/readonlyrest.yml
              readOnly: true
              subPath: readonlyrest.yml
            - name: ror-keystore
              mountPath: /usr/share/elasticsearch/config/rorkeystore.jks
              readOnly: true
              subPath: rorkeystore.jks
            - name: {{ include "persistentVolumeName" . }}
              mountPath: {{ .Values.volumeMounts.pv.mountPath }}
          {{- if .Values.data.resources }}
          resources: {{- toYaml .Values.data.resources | nindent 12 }}
          {{- end }}
          securityContext: {{- toYaml .Values.data.securityContext | nindent 12 }}
          env:
            - name: node.master
              value: "false"
            - name: node.data
              value: "true"
            - name: node.ingest
              value: "false"
            - name: network.host
              value: "{{ .Values.networkHost }}"
            - name: cluster.name
              value: "{{ .Values.clusterName }}"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "{{ template "kb-elastic.discoverySeedHosts" . }}"
            - name: node.max_local_storage_nodes
              value: {{ add .Values.master.replicaCount .Values.data.replicaCount .Values.ingest.replicaCount | quote }}
            - name: ELASTICSEARCH_HEAP_SIZE
              value: {{ .Values.data.heapSize | quote }}
            - name: ELASTICSEARCH_IS_DEDICATED_NODE
              value: "yes"
            - name: ELASTICSEARCH_NODE_TYPE
              value: "data"
            - name: ES_JAVA_OPTS
              value: "{{ .Values.esJavaOpts }}"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          ports:
            - name: {{ .Values.data.service.httpPortName }}
              containerPort: {{ .Values.data.service.httpPort }}
              protocol: TCP
            - name: {{ .Values.data.service.transportPortName }}
              containerPort: {{ .Values.data.service.transportPort }}
              protocol: TCP
          {{- if .Values.data.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.data.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.data.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.data.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.data.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.data.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.data.livenessProbe.httpGet.path }}
              port: {{ .Values.data.livenessProbe.httpGet.port }}
              scheme: {{ .Values.data.livenessProbe.httpGet.scheme }}
              httpHeaders:
                - name: Authorization
                  value: Basic ZWxhc3RpYzplbGFzdGlj
          {{- end }}
          {{- if .Values.data.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.data.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.data.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.data.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.data.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.data.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.data.readinessProbe.httpGet.path }}
              port: {{ .Values.data.readinessProbe.httpGet.port }}
              scheme: {{ .Values.data.readinessProbe.httpGet.scheme }}
              httpHeaders:
                - name: Authorization
                  value: Basic ZWxhc3RpYzplbGFzdGlj
          {{- end }}
{{- end }}
