apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kibanaConfigMapName" . }}
data:
  kibana.yml: |-
    xpack.graph.enabled: false
    xpack.ml.enabled: false
    xpack.monitoring.enabled: true
    xpack.security.enabled: false
    xpack.watcher.enabled: false    
