{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ include "kibanaIngressName" . }}
spec:
  tls:
  - host: 
    - {{ .Values.ingress.host }}
    secretName: kibana-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "kibanaServiceName" . }}
          servicePort: {{ .Values.service.port }}
{{- end }}
