apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  {{- if .Values.persistentVolumeClaim.namespace }}
  namespace: {{ .Values.persistentVolumeClaim.namespace }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaim.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storage }}
  volumeName: {{ .Values.persistentVolumeClaim.volumeName }}
