apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "persistentVolumeName" . }}
  labels:
    type: {{ .Values.persistentVolume.type }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
    - {{ .Values.persistentVolume.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.ReclaimPolicy }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.path }}
