{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kibanaServiceAccountName" . }}
  labels:
{{ include "kb-kibana.labels" . | indent 4 }}
{{- end -}}
