{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kb-kibana.serviceAccountName" . }}
  labels:
{{ include "kb-kibana.labels" . | indent 4 }}
{{- end -}}
