apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibanaServiceName" . }} 
  labels:
    app: {{ include "kibanaServiceName" . }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
{{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      protocol: TCP
      name: http
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ include "kibanaServiceName" . }}
