apiVersion: v1
kind: Service
metadata:
  name: kibana 
  labels:
    app: kibana
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpPort }}
      {{- if .Values.nodePort }}
      nodePort: {{ .Values.nodePort }}
      {{- end }}
      name: http
  selector:
    app: kibana
